apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tukr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tukr
    app.kubernetes.io/part-of: integ-app-kvyg
  name: hacbs-test-project-tukr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tukr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tukr
    spec:
      containers:
      - image: quay.io/bootstrap/integration1-zlxh-tenant/integ-app-kvyg/hacbs-test-project-tukr@sha256:74c56f0f59fdf3f0ce0cc9de7acdbf1812a43470b83342d9cba71bd4c5865ff2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
